version: 2.1
jobs:
  build-push-run:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout  # Get code from GitHub

      - run:
          name: Build Docker image
          command: docker build -t my-node-app .

      - run:
          name: Run the container
          command: docker run -d -p 8080:8080 --name my-node-container my-node-app

      - run:
          name: Wait for app to start
          command: sleep 5  # Give the app some time to boot up

      - run:
          name: Check if app is running
          command: curl http://127.0.0.1:8080

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Tag and push Docker image
          command: |
            docker tag my-node-app:latest $DOCKERHUB_USERNAME/my-node-app:latest
            docker push $DOCKERHUB_USERNAME/my-node-app:latest

